### ISSUE TITLE
wish: improve documentation

### ISSUE THREAD

**Issue by markstos** [danielsiwiec/parse-coords#1]
* Is `null` always returned if there an error? Does it ever throw?
  * For "lat, lon", is is the space required after the comma?
  * Are latitude and longitude validated to fall with the minimum and maximum ranges or are any numbers accepted?

**Comment by danielsiwiec** [comment]
Hi @markstos. Thanks for submitting the issue. I made some updates to the README. Could you take a peak and see if it is more clear now?

Regarding range validation, this is currently not supported, but I will welcome a PR for this!

**Comment by markstos** [comment]
@danielsiwiec It's clearer now. I will presume it never throws and only returns null if parsing fails. 

Regarding validation, you can see an example of range validation in the `parse-coordinates` module, which I maintain:

https://github.com/markstos/parse-coordinates/blob/master/index.js

**Comment by danielsiwiec** [comment]
Thank you @markstos . I'll close this issue, as it mostly related to documentation. Feel free to open a new issue for the range validation.
